### ISSUE TITLE
radio-tomography/software/listener-node$ make

### ISSUE THREAD

**Issue by lucasmhenrique** [timvandermeij/radio-tomography#3]
Dear Tim,
Thanks for your excellent work. It’s very well described.

However in the listener node part when i run the following commands to compile the listener node software 

$ cd ../../../software/listener-node
$ make
Iḿ getting this Erro:

lucas@lucas-VirtualBox:~/radio-tomography/software/listener-node$ make
sdcc -c -I/home/lucas/radio-tomography/software/listener-node/../../libraries/multi-spin-3.0/listener-node -I/home/lucas/radio-tomography/software/listener-node/../../libraries/cc-usb-firmware/source/components/usb/class_cdc -I/home/lucas/radio-tomography/software/listener-node/../../libraries/cc-usb-firmware/source/components/usb/library -I/home/lucas/radio-tomography/software/listener-node/../../libraries/cc-usb-firmware/source/components/common -I/home/lucas/radio-tomography/software/listener-node/../../libraries/cc-usb-firmware/source/components/common/cc8051 -I/home/lucas/radio-tomography/software/listener-node/../../libraries/cc-usb-firmware/source/components/targets/interface -I/home/lucas/radio-tomography/software/listener-node/../../libraries/cc-usb-firmware/source/components/targets/cc2531_dongle -I/home/lucas/radio-tomography/software/listener-node/../../libraries/cc-usb-firmware/source/components/utils -I/home/lucas/radio-tomography/software/listener-node/../../libraries/multi-spin-3.0/xpand2531 -I/home/lucas/radio-tomography/software/listener-node/../../libraries/cc-usb-firmware/source/components/radios/cc2530 -DNDEBUG -DBUF_SIZE=192 -DUSB_UART -Dchip=2531 --Werror --disable-warning 85 --disable-warning 84 --model-large --opt-code-size /home/lucas/radio-tomography/software/listener-node/../../libraries/multi-spin-3.0/listener-node/main.c -o /home/lucas/radio-tomography/software/listener-node/../../libraries/multi-spin-3.0/listener-node/main.rel
/home/lucas/radio-tomography/software/listener-node/../../libraries/multi-spin-3.0/listener-node/main.c:116: error 158: overflow in implicit constant conversion
Makefile:48: recipe for target '/home/lucas/radio-tomography/software/listener-node/../../libraries/multi-spin-3.0/listener-node/main.rel' failed
make: *** [/home/lucas/radio-tomography/software/listener-node/../../libraries/multi-spin-3.0/listener-node/main.rel] Error 1

I'm sorry, but I'm still new on Linux, if you can help me, I'll be very grateful!

Thank you so much.

**Comment by timvandermeij** [comment]
It looks like the compiler (SDCC) does not like the integer to character conversion happening on that line (since the structure in `rf.h` defines the field as a `char` and conversion from `int` to `char` may produce unexpected results). Refer to https://stackoverflow.com/a/5095500 for more information. Are you using the exact same version of SDCC as in the README?

Looking at this a bit more and `0xF5` is 245 in decimal, so it should fit in an `unsigned char` which has a range from 0 to 255. However, the structure in `rf.h` defines the field as a `char` (and apparently a `char` is a `signed char` in SDCC by default, see https://sourceforge.net/p/sdcc/mailman/message/32900834/, so that may overflow), so you may need to change that to be an `unsigned char`. Not sure why that never errored when we worked on it though if that is the case (and it was already like this in the original Multi-Spin library we used).

**Comment by lucasmhenrique** [comment]
Good morning, Tim. Thank you.

I'm using this version:

sdcc is already the newest version (3.5.0 + dfsg-2).
Thanks
